lib/clanserver_web/router.ex
defmodule ClanserverWeb.Router do
  use ClanserverWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authentication do
    plug ClanserverWeb.Authentication
  end

  pipeline :authorized do
    plug ClanserverWeb.Authentication
    plug ClanserverWeb.Authorization
  end

  scope "/", ClanserverWeb do
    pipe_through :browser

  end

  scope "/", ClanserverWeb do
    pipe_through [:browser, :authentication]
    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true
    resources "/users", UserController, only: [:new, :create]
  end

  scope "/", ClanserverWeb do
    pipe_through [:browser, :authorized]
    get "/", PageController, :index
    resources "/clans", ClanController
    resources "/invites", InviteController
    get "/inviteuser/:id", InviteController, :invite_user
    get "/removeuser/:id", InviteController, :remove_user_from_clan
    get "/my_invites", InviteController, :my_invites
    get "/accept_invite/:id", InviteController, :accept_invite
    get "/clan_list", ClanController, :clan_list
    get "/clan_listing", ClanController, :listing
    get "/user_list", UserController, :listing
#    get "/invites/new", InviteController, :new
    resources "/users", UserController, only: [:delete, :index, :show, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", ClanserverWeb do
  #   pipe_through :api
  # end
end

lib/clanserver_web/views/layout_view.ex
defmodule ClanserverWeb.LayoutView do
  use ClanserverWeb, :view
end

lib/clanserver_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Clanserver · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
                  <%= if @conn.assigns.current_user do %>
                  <div>
                  <%= if @conn.assigns.current_user.clan do %>[<%= @conn.assigns.current_user.clan.clantag %>]<% end %><%= @conn.assigns.current_user.nickname %>


                  </div>

                      <%= link "Sign out", to: Routes.session_path(@conn, :delete), class: "navbar-item", method: :delete %>
                      <% end %>
          <ul>
            <li></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <span><%= link "Users", to: Routes.user_path(@conn, :listing) %></span>
      <span><%= link "Clans", to: Routes.clan_path(@conn, :listing) %></span>
      <span><%= link "Invites", to: Routes.invite_path(@conn, :my_invites) %></span>
      <span><%= link "My subordinate", to: Routes.clan_path(@conn, :clan_list) %></span>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>